# data_class: leverOddball
results_dir: /scratch2/weka/millerlab/eisenaj/UniversalUnconsciousness
# results_dir_engaging: /orcd/data/ekmiller/001/eisenaj/UniversalUnconsciousness
# results_dir: null
delase_results_dir: ${params.results_dir}/DeLASE_results
grid_search_results_dir: ${params.results_dir}/grid_searches
noise_filter_results_dir: ${params.results_dir}/noise_filter_info
all_data_dir: '/scratch2/weka/millerlab/eisenaj/datasets'
# all_data_dir: /orcd/data/ekmiller/001/common/datasets
# all_data_dir: null
data_class: anesthesiaLvrOdd
# data_class: propofolPuffTone
session: null
area: null
run_index: 0
random_state: 42
areas: ['all']
# areas: ['all', 'vlPFC', 'FEF', '7b', 'CPB'] # propofol
# areas: ['vlPFC-L', 'vlPFC-R', 'dlPFC-L', 'dlPFC-R'] # anesthesiaLvrOdd

testing: False

window: 15
T_pred: null

# grid search
# grid_set: grid_set4 # grid set name # ANESTHESIALVRODD
# grid_set: grid_set5 # grid set name # PROPOFOLPUFFTONE
grid_set: grid_set6 # grid set name # ALL AND PROPOFOL PUFF TONE SINGLES
# grid_set: grid_set7 # grid set name # ANESTHESIA LVRODD SINGLES
num_windows_per_section: 4
group_ranks: True # group ranks so that the same CPU is used for all ranks
stat_to_use: aic
sections_to_use: ['all_sections']
# sections_to_use: ['awake oddball', 'unconscious oddball', 'recovery oddball']
compute_delase_on_grid: False
# compute_delase_on_grid: True

# full analysis
stride: 15
# reduced analysis time by increasing stride
# stride: 120
n_delays: null
rank: null

# stability
max_freq: 300
max_unstable_freq: 125

# filtering noise windows
noise_filter: True
wake_amplitude_thresh: 1
anesthesia_amplitude_thresh: 1
electrode_num_thresh: 1

# preprocessing
pca: False
pca_thresh: 0.95
pca_dims: null
normed: False
subsample: 1
# low_pass: 80
# high_pass: 30
low_pass: 0.1
high_pass: 4
# low_pass: null
# high_pass: null
